spring:
  profiles:
    active: test

---
spring:
  profiles: dev
  pplication:
    name: microservicecloud-config-dev

---
spring:
  profiles: test
  pplication:
    name: microservicecloud-config-test

